### Load the libraries needed

In [1]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd

### Load the Data

In [2]:
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

### Data Preprocessing

In [3]:
# mapping sex column to numeric values
df["sex"] = df["sex"].map({"female": 1, "male": 0})
# mapping smoker column to numeric values
df["smoker"] = df["smoker"].map({"yes": 1, "no": 0})
df.head()

   age  sex     bmi  children  smoker     region      charges
0   19    1  27.900         0       1  southwest  16884.92400
1   18    0  33.770         1       0  southeast   1725.55230
2   28    0  33.000         3       0  southeast   4449.46200
3   33    0  22.705         0       0  northwest  21984.47061
4   32    0  28.880         0       0  northwest   3866.85520

In [4]:
# interaction feautres
df["age_smoker"] = df["age"] * df["smoker"]
df["bmi_smoker"] = df["bmi"] * df["smoker"]
df.head()

,age,sex,bmi,children,smoker,region,charges,age_smoker,bmi_smoker
0,19,1,27.900,0,1,southwest,16884.92400,19,27.9
1,18,0,33.770,1,0,southeast,1725.55230,0,0.0
2,28,0,33.000,3,0,southeast,4449.46200,0,0.0
3,33,0,22.705,0,0,northwest,21984.47061,0,0.0
4,32,0,28.880,0,0,northwest,3866.85520,0,0.0

### Split the data into **dependent** and **independent** variables

In [5]:
# Drop charges and region column
x = df.drop(columns=["charges", "region"], axis=1)
# independent
x.head()

   age  sex     bmi  children  smoker  age_smoker  bmi_smoker
0   19    1  27.900         0       1          19        27.9
1   18    0  33.770         1       0           0         0.0
2   28    0  33.000         3       0           0         0.0
3   33    0  22.705         0       0           0         0.0
4   32    0  28.880         0       0           0         0.0

In [6]:
# dependent
y = df.charges
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

### Split the data into **training** and **testing** part

In [7]:
# import train test split
from sklearn.model_selection import train_test_split

In [8]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state = 1)

In [9]:
len(train_x), len(test_x), len(train_y), len(test_y)

(1070, 268, 1070, 268)

### Create Model

In [10]:
# Create object
lasso_model = Lasso(alpha=0.5)

In [11]:
# Pass the values to train the model
lasso_model.fit(train_x, train_y)

Lasso(alpha=0.5)

In [12]:
# predict the values from the model
y_pred = lasso_model.predict(test_x)

In [13]:
# calculate mean_squared_error
mse = mean_squared_error(test_y, y_pred)
print("MSE: ", mse)

MSE:  21660616.676332444

### LassoCV

In [14]:
# import LassoCV
from sklearn.linear_model import LassoCV

In [15]:
# alpha values list
alphas = [0.001, 0.1, 1, 2, 5, 10, 20, 30, 40, 50, 100]

lasso_cv_model = LassoCV(
    alphas=alphas,
    cv=5,
    max_iter=1000,
    random_state=42
)

lasso_cv_model.fit(train_x, train_y)

LassoCV(alphas=[0.001, 0.1, 1, 2, 5, 10, 20, 30, 40, 50, 100], cv=5,
        random_state=42)

In [16]:
# best alpha value
print("Best alpha: ", lasso_cv_model.alpha_)

Best alpha:  2.0

In [17]:
# predict values from the model
y_pred = lasso_cv_model.predict(test_x)

In [18]:
# calculate mean_squared_error
mse = mean_squared_error(test_y, y_pred)
print("MSE: ", mse)

MSE:  21669733.947112434

In [19]:
# calculate r2 score
r2 = r2_score(test_y, y_pred)
print("r2 score: ", r2)

r2 score:  0.8548389529700395